name: Simple Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Optional: build your app, e.g., for Node.js
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      # Deploy via SSH (replace with your own deploy script/commands)
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: your-ssh-username
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            cd /path/to/your/app
            git pull
            docker compose up -d --build
